### PR TITLE
588 matexp fortran

### LINKED ISSUE #588: Correct by October 10 or be kicked off of CRAN.
```
checking usage of KIND in Fortran files ... WARNING
Found the following file with non-portable usage of KIND:
  matexp.f
For details set environment variable _R_CHECK_FORTRAN_KIND_DETAILS_ to
a true value.
```

```
NOTE
Documented arguments not in \usage in documentation object 'rxErrTypeCombine':
  ‘newTransform’

Documented arguments not in \usage in documentation object 'rxRepR0_':
  ‘number’

Documented arguments not in \usage in documentation object 'rxSetupScale':
  ‘inits’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

### PR DESCRIPTION
**Pull request by mattfidler**
Close #588

### CODE REVIEW

**Comment by mattfidler** [comment]
Wait to see if I can do more by Oct 10?

**Comment by billdenney** [comment]
I'd like to try to fix the factor lost level issue that I brought up last night in nlmixr2est (not sure if it will end up here, but I think so).

**Comment by mattfidler** [comment]
I would like to get the `linCmt()` fixed.  That is first on my priority list.  

The nlmixr2est lost factor is likely here; I'm unsure if I can do that by the 10th; it is even less likely that the factor will be fixed by then, but here is hoping

**Comment by mattfidler** [comment]
I am keeping this pull request since it is based on the current rxode2 release and therefore could be submitted to CRAN as is.

I think the `KIND` is a false positive since it was simply in the fortran comments (commented out code).

**Pull request merged**
