### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by billdenney**
Update CI to new versions

### CODE REVIEW

**Comment by mattfidler** [comment]
It seems that these jobs are getting killed.  They used to be able to run to completion.

**Comment by mattfidler** [comment]
My guess is the rstudo guys added a kill switch to their continuous integration scripts.  According to github

https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

It should be 6 hours.

I don't know who exactly to bother here or if we need to host our own scripts (or place some options etc)

**Comment by billdenney** [comment]
I wonder if I was running too many.  GitHub also limits concurrency.  I didn't see anything on the RStudio side that suggested that they had a kill switch.

**Comment by mattfidler** [comment]
With less checks, I am rerunning the release ubuntu.  Maybe the concurrency is the issue..

**Comment by mattfidler** [comment]
Looks good.  Thanks

**Pull request merged**
