### PR TITLE
Crash when simulating a model with a `dur` column

### PR DESCRIPTION
**Pull request by mattfidler**
I'm working to make a reprex, but in case it's obvious, here is the back trace:

```
  nlmixr(
    d$model,
    data = d$data,
    est = "rxSolve",
    control = list(keep = c("target_name", "kd_glytac_target", "conc_target_ss", "hl_target", "route", "dose_amt", "EXFRQ", "conc_target_ss_mg_mL"))
  )
Loading required package: nlmixr2data
[New Thread 0x7ffff37b2640 (LWP 1453118)]
[Detaching after vfork from child process 1453160]
[Detaching after vfork from child process 1453162]
[Detaching after vfork from child process 1453167]

Thread 1 "R" received signal SIGSEGV, Segmentation fault.
0x00007ffff7c0f970 in Rf_asLogical2 () from /usr/lib/R/lib/libR.so
(gdb) bt
#0  0x00007ffff7c0f970 in Rf_asLogical2 () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#1  0x00007ffff2c3c660 in serializeToRaw (object=0x555555570e98, versionSexp=<optimized out>, useXdrSexp=0x19)
    at serialize.cpp:228
nlmixr2/nlmixr2est#2  0x00007ffff2a98fc7 in writeObject<CompressBuffer<vec_wrapper, lz4_compress_env> > (sobj=sobj@entry=0x7fffffff4d80,
    x=<optimized out>) at /tmp/RtmpirMnr4/R.INSTALL265ffb48d9aeab/qs/src/qs_common.h:908
nlmixr2/nlmixr2est#3  0x00007ffff2a99abe in writeObject<CompressBuffer<vec_wrapper, lz4_compress_env> > (sobj=sobj@entry=0x7fffffff4d80,
    x=<optimized out>, x@entry=0x55555a438d08) at /tmp/RtmpirMnr4/R.INSTALL265ffb48d9aeab/qs/src/qs_serialize_common.h:586
nlmixr2/nlmixr2est#4  0x00007ffff2a373f7 in qserialize (x=x@entry=0x55555a438d08, preset="fast", algorithm="zstd",
    compress_level=compress_level@entry=4, shuffle_control=shuffle_control@entry=15, check_hash=<optimized out>)
    at qs_functions.cpp:264
nlmixr2/nlmixr2est#5  0x00007ffff2a14f72 in _qs_qserialize_try (xSEXP=0x55555a438d08, presetSEXP=<optimized out>,
    algorithmSEXP=<optimized out>, compress_levelSEXP=<optimized out>, shuffle_controlSEXP=<optimized out>,
    check_hashSEXP=<optimized out>) at RcppExports.cpp:682
nlmixr2/nlmixr2est#6  0x00007ffff2a1518b in _qs_qserialize (xSEXP=<optimized out>, presetSEXP=<optimized out>, algorithmSEXP=<optimized out>,
    compress_levelSEXP=<optimized out>, shuffle_controlSEXP=<optimized out>, check_hashSEXP=<optimized out>)
    at RcppExports.cpp:689
nlmixr2/nlmixr2est#7  0x00007ffff7c4f27a in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#8  0x00007ffff7c92688 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#9  0x00007ffff7ca619d in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#10 0x00007ffff7ca650b in Rf_eval () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2extra#1 0x00007ffff7ca86df in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#12 0x00007ffff7ca94c7 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#13 0x00007ffff7ca663c in Rf_eval () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2extra#3 0x00007ffff7caa238 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#15 0x00007ffff7ca6936 in Rf_eval () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#16 0x00007ffff7ca86df in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#17 0x00007ffff7ca94c7 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#18 0x00007ffff7c93dc3 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#19 0x00007ffff7ca619d in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#20 0x00007ffff7ca650b in Rf_eval () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#21 0x00007ffff7ca86df in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#22 0x00007ffff7ca94c7 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#23 0x00007ffff7ca9eed in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#24 0x00007ffff7cef5a4 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#25 0x00007ffff7cefc71 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#26 0x00007ffff7cefff2 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#27 0x00007ffff7c8b01f in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#28 0x00007ffff7ca619d in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#29 0x00007ffff7ca650b in Rf_eval () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#30 0x00007ffff7ca86df in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/rxode2#7 0x00007ffff7ca94c7 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#32 0x00007ffff7ca663c in Rf_eval () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#33 0x00007ffff7cdccea in Rf_ReplIteration () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#34 0x00007ffff7cdd080 in ?? () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#35 0x00007ffff7cdd140 in run_Rmainloop () from /usr/lib/R/lib/libR.so
nlmixr2/nlmixr2est#36 0x000055555555509f in main ()
nlmixr2/nlmixr2est#37 0x00007ffff7952d90 in __libc_start_call_main (main=main@entry=0x555555555080 <main>, argc=argc@entry=3,
    argv=argv@entry=0x7fffffffe3b8) at ../sysdeps/nptl/libc_start_call_main.h:58
--Type <RET> for more, q to quit, c to continue without paging--c
nlmixr2/nlmixr2est#38 0x00007ffff7952e40 in __libc_start_main_impl (main=0x555555555080 <main>, argc=3, argv=0x7fffffffe3b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe3a8) at ../csu/libc-start.c:392
nlmixr2/nlmixr2est#39 0x00005555555550d5 in _start ()
```

### CODE REVIEW

**Comment by mattfidler** [comment]
@billdenney this branch will no longer crash, though it does not give the correct results.

**Comment by mattfidler** [comment]
@billdenney 

Now this will give correct results; have taken out locf interpolaton for covariates.  

Will add an option for the following interpolations:

- `locf`
- `nocb`
- `na`

These will tell what will be imputed in the `keep` column when the doses are extrapolated.  This will occur in something like `addDosing=TRUE`

**Comment by billdenney** [comment]
Thanks for the quick fix on this.  It worked for my issue.

**Comment by mattfidler** [comment]
Great! glad to hear it

**Pull request merged**
