### PR TITLE
Rxode closes #17

### LINKED ISSUE #17: Questions During Test Update PR Generation
I'm currently working on a test update to switch to testthat edition 3 and to try to make the tests silent when successful.

During that, I have a few questions:

1. Similar to the suggestion in nlmixr2, I think it would be helpful and simplifying to switch the testing to remove the rxode2Test function.  Do you agree?
2. There are a bunch of calls like `.rx <- loadNamespace("rxode2")`.  Would it be okay to switch all of those to be `rxode2:::` instead of `.rx$` to make it a bit clearer what is happening in the tests?  But, I'm not certain that all the `.rx$` calls are all just doing the same as `:::`.  I don't think it could be a search-and-replace simple switch.
3. Many of the tests reset the random number generator with set.seed().  I think that it would be better to use `withr::with_seed()`.  Do you agree?
4. Longer-term, I think it would be helpful to move the tests like `test-rxode-issue-050.R` to be in a test file that points to the function being tested.  Do you agree with that one?
5. Several tests suggest that they require the `units` library.  Do you know if the units library is really required?
6. When running tests in parallel, they tend to stop because of "rxode2 already building model, waiting for lock file removal".  Is there a way to make this not an error or less strict?  I can imagine using nlmixrtargets in a way where multiple models may be built simultaneously, too.  (Though, I've also had some places where I've made errors in updating the testing, so maybe this is a non-issue.)

### PR DESCRIPTION
**Pull request by mattfidler**
Rxode closes #17

### CODE REVIEW

**Comment by mattfidler** [comment]
@billdenney 

With the new testing framework, there seems to be many many more skips than what was in the last test.  There also seems to be more failures on my system.  

Just an observation.  I think the skips are not related to  pull request #16, though the failures may be related.

**Comment by mattfidler** [comment]
It seems the skips are from `vdiffr`.  I have heard that it doens't play well with `testthat3`. I had forgotten though.

**Comment by mattfidler** [comment]
They of course released a new version.  It should work with vidiffr.  However, the number of svg files means that the snapshots cannot be included in the CRAN release. 

I think this should be OK...

**Comment by billdenney** [comment]
I just reran the tests with main as pulled right now.  On my system, I see 12 failures, 4 warnings, 1 skip, and 12652 passes which I think is the same number I started with.  It looks like you're in the middle of fixing these, but if you'd like me to step in, I can.

The failures appear to be due to:

An issue that I accidentally introduced:

* at `test-rxIs.R:11` where changing `select` to `dplyr::select` and `mutate` to `dplyr::mutate` throughout should fix it

And several issues that were there from the beginning on my system:

* small differences in `test-lincmt-solve.R` (4 failures; I think that those were there in all of my tests)
* missing warnings in `test-etTrans.R` (2 failures; I will drop the `expect_warnings()` on line 604 in favor of just using `suppressWarnings()`.
* A small difference in `test-rxode-issue-007.R:15` (1 failure that would be fixed by changing the tolerance to 1e-3 or changing the expected value at location 62 in the vector to 0.00009461)
* an error at `test-progress.R:18` that I saw all the time I was testing it, but I didn't understand the goal of the test
* two errors in `test-modelVars.R:38` and `test-modelVars.R:39` that were due to hash mismatches that I don't understand where the hash is coming from.
* missing `dur` in `test-et.R:2` where I didn't see the needed column of `dur` in the source data

**Comment by mattfidler** [comment]
I just migrated the snapshots.  My failures was because my vdiffr wasn't upgraded...

What is a bit concerning is that everything seems successful when running it in CI but not when running it locally.

**Comment by mattfidler** [comment]
Some of these failures were not present when I last ran the tests, but I'm unsure what the cause is... 

They seem rather minor in general

**Comment by mattfidler** [comment]
By the way, I forgot to say thank you.  This is alot of work.  It has been on my todo for a long time

**Comment by mattfidler** [comment]
Commit 7cc81368 matches the tests of `lincmt-solve` but has the errors because `focei` moved more to `nlmixr2`

**Comment by mattfidler** [comment]
For `lincmt-solve`, bisection reveals;
```
a5a0bf2482cc0f19ba1d29ea03171ca30eb8b795 is the first bad commit
commit a5a0bf2482cc0f19ba1d29ea03171ca30eb8b795
Author: Bill Denney <wdenney@humanpredictions.com>
Date:   Wed Jan 19 09:29:55 2022 -0500

    Update to testthat edition 3, make testing parallel, update tests for some simple failures, make testing silent with success

 DESCRIPTION                           |   2 +
 tests/testthat/test-000sum.R          |   3 +-
 tests/testthat/test-100-cmt.R         |   4 -
 tests/testthat/test-alag.R            |  43 ++++----
    Update to testthat edition 3, make testing parallel, update tests for some simple failures, make testing silent with success

    Update to testthat edition 3, make testing parallel, update tests for some simple failures, make testing silent with success

 DESCRIPTION                           |   2 +
 tests/testthat/test-000sum.R          |   3 +-
 tests/testthat/test-100-cmt.R         |   4 -
 tests/testthat/test-alag.R            |  43 ++++----
 DESCRIPTION                           |   2 +
 tests/testthat/test-000sum.R          |   3 +-
 tests/testthat/test-100-cmt.R         |   4 -
 tests/testthat/test-alag.R            |  43 ++++----
 tests/testthat/test-backward.R        |   2 -
 tests/testthat/test-bad-dose.R        |   1 -
 tests/testthat/test-basic.R           |   1 -
 tests/testthat/test-bioavailibility.R |  11 +-
 tests/testthat/test-cholperm.R        |   6 --
 tests/testthat/test-cmt-order.R       |  15 ++-
 tests/testthat/test-cov.R             |  12 +--
 tests/testthat/test-cvpost.R          |   3 -
 tests/testthat/test-data-frame.R      |  10 +-
 tests/testthat/test-data-table.R      |   1 -
 tests/testthat/test-deSolve-events.R  |   1 -
 tests/testthat/test-derived.R         |   2 -
 tests/testthat/test-dfRep.R           |   3 +-
 tests/testthat/test-dfdy.R            |   3 -
 tests/testthat/test-dollar-names.R    |   8 +-
 tests/testthat/test-dplyr.R           |   5 +-
 tests/testthat/test-drop.R            |   3 +-
 tests/testthat/test-dsl.R             |   6 +-
 tests/testthat/test-et.R              |  31 ++----
 tests/testthat/test-etTrans.R         |  27 ++---
 tests/testthat/test-evid2.R           |   3 -
 tests/testthat/test-evid3.R           |   2 -
 tests/testthat/test-example-3-1.R     |   2 +-
 tests/testthat/test-example-3-2.R     |   4 -
 tests/testthat/test-example-3-3.R     |   3 -
 tests/testthat/test-example-3-5-1.R   |   4 +-
 tests/testthat/test-example-6.R       |   3 -
 tests/testthat/test-expand-grid.R     |  16 ++-
 tests/testthat/test-factorial.R       |  11 +-
 tests/testthat/test-fun.R             |   2 -
 tests/testthat/test-gammap.R          |  11 +-
 tests/testthat/test-gc.R              |   3 -
 tests/testthat/test-getindex.R        |   2 -
 tests/testthat/test-hmax.R            |   2 -
 tests/testthat/test-idFactor.R        |   6 +-
 tests/testthat/test-ifelse.R          |   1 -
 tests/testthat/test-ignore-state.R    |   2 +-
 tests/testthat/test-ind-lin.R         |  22 ++--
 tests/testthat/test-ini.R             |  12 +--
 tests/testthat/test-keep.R            |   2 +-
 tests/testthat/test-lag.R             |  13 +--
 tests/testthat/test-lhs-ifelse.R      |   2 +-
 tests/testthat/test-lhs-param.R       |   2 +-
 tests/testthat/test-lincmt-parse.R    |  10 +-
 tests/testthat/test-lincmt-solve.R    | 187 ++++++++++++++++----------------
 tests/testthat/test-load.R            |   3 +-
 tests/testthat/test-lock.R            |   2 +-
 tests/testthat/test-logical.R         |  12 +--
 tests/testthat/test-logit.R           |   6 +-
 tests/testthat/test-mdv.R             |   1 -
 tests/testthat/test-missing-evid.R    |   3 +-
 tests/testthat/test-model-rate.R      |   6 +-
 tests/testthat/test-modelVars.R       |   1 -
 tests/testthat/test-modelargs.R       |   2 +-
 tests/testthat/test-mtime.R           |   2 -
 tests/testthat/test-multi.R           |   3 +-
 tests/testthat/test-na.R              |   6 +-
 tests/testthat/test-named-id.R        |   4 +-
 tests/testthat/test-newind.R          |   2 +-
 tests/testthat/test-occ.R             |   2 +-
 tests/testthat/test-off.R             |   2 +-
 tests/testthat/test-omega-chol.R      |   3 +-
 tests/testthat/test-opt-expr.R        |   2 -
 tests/testthat/test-par-solve.R       |   2 +-
 tests/testthat/test-param-order.R     |   2 -
 tests/testthat/test-parsing.R         |   2 +-
 tests/testthat/test-phi.R             |   2 +-
 tests/testthat/test-pipeline.R        |   3 +-
 tests/testthat/test-plot.R            |   1 -
 tests/testthat/test-progress.R        |   1 -
 tests/testthat/test-random.R          | 195 ++++++++++++++--------------------
 tests/testthat/test-resample.R        |  93 ++++++++--------
 tests/testthat/test-reset.R           |   4 +-
 tests/testthat/test-rhs.R             |   6 +-
 tests/testthat/test-rlkj.R            |  12 +--
 tests/testthat/test-rm-dll.R          |   2 +-
 tests/testthat/test-rxIs.R            |   4 +-
 tests/testthat/test-rxRmvn.R          |   1 -
 tests/testthat/test-rxode-issue-004.R |   2 +-
 tests/testthat/test-rxode-issue-005.R |   2 +-
 tests/testthat/test-rxode-issue-007.R |  21 +++-
 tests/testthat/test-rxode-issue-050.R |   1 -
 tests/testthat/test-rxode-issue-054.R |  16 ++-
 tests/testthat/test-rxode-issue-056.R |   3 +-
 tests/testthat/test-rxode-issue-067.R |   3 +-
 tests/testthat/test-rxode-issue-117.R |   2 +-
 tests/testthat/test-rxode-issue-160.R |   3 +-
 tests/testthat/test-rxode-issue-163.R |   2 +-
 tests/testthat/test-rxode-issue-169.R |   2 +-
 tests/testthat/test-rxode-issue-178.R |   3 +-
 tests/testthat/test-rxode-issue-213.R |   3 +-
 tests/testthat/test-rxode-issue-299.R |   1 -
 tests/testthat/test-rxode-issue-468.R |   6 +-
 tests/testthat/test-scale.R           |   2 +-
 tests/testthat/test-seq.R             |   6 +-
 tests/testthat/test-steady-state.R    |  14 +--
 tests/testthat/test-symmetric.R       |  14 +--
 tests/testthat/test-tad.R             |   6 +-
 tests/testthat/test-theta-eta.R       |   3 -
 tests/testthat/test-transit.R         |   2 +-
 tests/testthat/test-ui-piping.R       | 154 ++++++++++++++++-----------
 tests/testthat/test-zzzzz.R           |   8 +-
 106 files changed, 531 insertions(+), 670 deletions(-)
```

**Comment by billdenney** [comment]
I'm glad that it's helpful!  Since I'm starting to help with testing, it's also a a bit selfish. :)

**Comment by mattfidler** [comment]
It would be even better if when the testing failed, it showed it failed...

**Comment by mattfidler** [comment]
I'm unsure what to do with something like this:

```r
Error : testthat subprocess exited in file `test-plot.R`
```

Also in addition to what Bill mentioned:

```
Failure (test-backward.R:167:7): Add sampling makes sense
tmp$time[2] (`actual`) not equal to 0.5 (`expected`).

`class(actual)` is a character vector ('units')
`class(expected)` is absent

`attr(actual, 'units')` is an S3 object of class <symbolic_units>, a list
`attr(expected, 'units')` is absent

Failure (test-backward.R:168:7): Add sampling makes sense
x$time[2] (`actual`) not equal to 1 (`expected`).

`class(actual)` is a character vector ('units')
`class(expected)` is absent

`attr(actual, 'units')` is an S3 object of class <symbolic_units>, a list
`attr(expected, 'units')` is absent

Failure (test-backward.R:171:7): Add sampling makes sense
x$time[2] (`actual`) not equal to 0.5 (`expected`).

`class(actual)` is a character vector ('units')
`class(expected)` is absent

`attr(actual, 'units')` is an S3 object of class <symbolic_units>, a list
`attr(expected, 'units')` is absent

Failure (test-backward.R:190:7): Changing sampling makes sense.
min(x$t) (`actual`) not equal to 0 (`expected`).

`class(actual)` is a character vector ('units')
`class(expected)` is absent

`attr(actual, 'units')` is an S3 object of class <symbolic_units>, a list
`attr(expected, 'units')` is absent

Failure (test-backward.R:191:7): Changing sampling makes sense.
max(x$t) (`actual`) not equal to 5 (`expected`).

`class(actual)` is a character vector ('units')
`class(expected)` is absent

`attr(actual, 'units')` is an S3 object of class <symbolic_units>, a list
`attr(expected, 'units')` is absent

```

**Comment by mattfidler** [comment]
It now (accurately) shows the tests fail

**Comment by mattfidler** [comment]
```
[ FAIL 48 | WARN 21 | SKIP 1 | PASS 8236 ]
```

**Comment by mattfidler** [comment]
```
── Failure (test-cmt-order.R:145:7): Compartment melding with dvid ─────────────
tmp$CMT[tmp$ID == 1] (`actual`) not equal to c(...) (`expected`).

`actual` is NULL
`expected` is an integer vector (1, 5, 5, 5, 5, ...)
── Failure (test-cmt-order.R:183:7): Compartment melding with dvid ─────────────
tmp$CMT[tmp$ID == 1] (`actual`) not equal to c(...) (`expected`).

`actual` is NULL
`expected` is an integer vector (1, 5, 5, 5, 5, ...)
── Failure (test-cov.R:413:9): time varying covariates lhs ─────────────────────
x1$CL (`actual`) not equal to x2$CL (`expected`).

`actual` is a double vector (2.4, 2.4, 2.4, 2.4, 2.4, ...)
`expected` is NULL
── Failure (test-etTrans.R:124:9): EVID=4 makes sense ──────────────────────────
expect_warning(.rx$etTrans(et, mod, keepDosingOnly = TRUE)$EVID) (`actual`) not equal to c(3L, 101L) (`expected`).

`actual` is an S3 object of class <simpleWarning/warning/condition>, a list
`expected` is an integer vector (3, 101)
── Failure (test-etTrans.R:489:9): X(0) should be at time zero; see issue #105 ──
dat1$TIME (`actual`) not equal to RawData2$TIME (`expected`).

`actual` is NULL
`expected` is a double vector (3, 4, 5, 3, 4, ...)
── Failure (test-etTrans.R:526:9): censoring checks ────────────────────────────
attr(class(ret), ".rxode2.lst")$censAdd (`actual`) not equal to 0L (`expected`).

`actual` is NULL
`expected` is an integer vector (0)
── Failure (test-etTrans.R:527:9): censoring checks ────────────────────────────
attr(class(ret), ".rxode2.lst")$limitAdd (`actual`) not equal to 0L (`expected`).

`actual` is NULL
`expected` is an integer vector (0)
── Failure (test-etTrans.R:625:9): etTrans drop levels are correct ─────────────
attr(class(tmp), ".rxode2.lst")$idLvl (`actual`) not equal to `lvls` (`expected`).

`actual` is NULL
`expected` is a character vector ('32', '33', '35', '36', '37', ...)
── Failure (test-etTrans.R:626:9): etTrans drop levels are correct ─────────────
levels(tmp$ID) (`actual`) not equal to `lvls` (`expected`).

`actual` is NULL
`expected` is a character vector ('32', '33', '35', '36', '37', ...)
── Failure (test-etTrans.R:124:9): EVID=4 makes sense ──────────────────────────
expect_warning(.rx$etTrans(et, mod, keepDosingOnly = TRUE)$EVID) (`actual`) not equal to c(3L, 101L) (`expected`).

`actual` is an S3 object of class <simpleWarning/warning/condition>, a list
`expected` is an integer vector (3, 101)
── Failure (test-etTrans.R:489:9): X(0) should be at time zero; see issue #105 ──
dat1$TIME (`actual`) not equal to RawData2$TIME (`expected`).

`actual` is NULL
`expected` is a double vector (3, 4, 5, 3, 4, ...)
── Failure (test-etTrans.R:526:9): censoring checks ────────────────────────────
attr(class(ret), ".rxode2.lst")$censAdd (`actual`) not equal to 0L (`expected`).

`actual` is NULL
`expected` is an integer vector (0)
── Failure (test-etTrans.R:527:9): censoring checks ────────────────────────────
attr(class(ret), ".rxode2.lst")$limitAdd (`actual`) not equal to 0L (`expected`).

`actual` is NULL
`expected` is an integer vector (0)
── Failure (test-etTrans.R:625:9): etTrans drop levels are correct ─────────────
attr(class(tmp), ".rxode2.lst")$idLvl (`actual`) not equal to `lvls` (`expected`).

`actual` is NULL
`expected` is a character vector ('32', '33', '35', '36', '37', ...)
── Failure (test-etTrans.R:626:9): etTrans drop levels are correct ─────────────
levels(tmp$ID) (`actual`) not equal to `lvls` (`expected`).

`actual` is NULL
`expected` is a character vector ('32', '33', '35', '36', '37', ...)
── Error (test-idFactor.R:99:7): Test giving IDs to data-frames ────────────────
Error in `as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors)`: cannot coerce class 'c("simpleWarning", "warning", "condition")' to a data.frame
Backtrace:
    █
 1. ├─testthat::expect_equal(data.frame(tmp1), data.frame(tmp2)) test-idFactor.R:99:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. └─base::data.frame(tmp1)
 5.   ├─base::as.data.frame(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors)
 6.   └─base::as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors)
── Error (test-idFactor.R:190:7): test iCov ID ─────────────────────────────────
Error in `as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors)`: cannot coerce class 'c("simpleWarning", "warning", "condition")' to a data.frame
Backtrace:
    █
 1. ├─testthat::expect_equal(data.frame(tmp1), data.frame(tmp2)) test-idFactor.R:190:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. └─base::data.frame(tmp1)
 5.   ├─base::as.data.frame(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors)
 6.   └─base::as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors)
── Error (test-rhs.R:24:7): rxSolve produces the correct results for rhs ───────
Error in `as.data.frame.default(o1)`: cannot coerce class 'c("simpleWarning", "warning", "condition")' to a data.frame
Backtrace:
    █
 1. ├─testthat::expect_equal(...) test-rhs.R:24:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. ├─base::as.data.frame(o1)
 5. └─base::as.data.frame.default(o1)
── Error (test-transit.R:41:7): Transit absorption is not specified, but still works. ──
Error in `transit[c(1:15, seq(194 - 15, 194)), ]`: incorrect number of dimensions
Backtrace:
    █
 1. ├─testthat::expect_equal(...) test-transit.R:41:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. └─base::as.data.frame(transit[c(1:15, seq(194 - 15, 194)), ])
── Error (test-transit.R:76:7): Transit absorption using lagmma1p works. ───────
Error in `transit[c(1:15, seq(194 - 15, 194)), ]`: incorrect number of dimensions
Backtrace:
    █
 1. ├─testthat::expect_equal(...) test-transit.R:76:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. └─base::as.data.frame(transit[c(1:15, seq(194 - 15, 194)), ])
── Error (test-transit.R:101:7): Transit absorption using C's lgamma function. ──
Error in `transit[c(1:15, seq(194 - 15, 194)), ]`: incorrect number of dimensions
Backtrace:
    █
 1. ├─testthat::expect_equal(...) test-transit.R:101:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. └─base::as.data.frame(transit[c(1:15, seq(194 - 15, 194)), ])
── Error (test-transit.R:122:7): Transit absorption using lfactorial ───────────
Error in `transit[c(1:15, seq(194 - 15, 194)), ]`: incorrect number of dimensions
Backtrace:
    █
 1. ├─testthat::expect_equal(...) test-transit.R:122:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. └─base::as.data.frame(transit[c(1:15, seq(194 - 15, 194)), ])
── Error (test-transit.R:143:7): Transit absorption using log(factorial) ───────
Error in `transit[c(1:15, seq(194 - 15, 194)), ]`: incorrect number of dimensions
Backtrace:
    █
 1. ├─testthat::expect_equal(...) test-transit.R:143:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. └─base::as.data.frame(transit[c(1:15, seq(194 - 15, 194)), ])
── Error (test-transit.R:163:7): Transit absorption is function that can take 2 arguments ──
Error in `as.data.frame.default(transit)`: cannot coerce class 'c("simpleWarning", "warning", "condition")' to a data.frame
Backtrace:
    █
 1. ├─testthat::expect_equal(...) test-transit.R:163:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. ├─base::as.data.frame(transit)
 5. └─base::as.data.frame.default(transit)
── Error (test-transit.R:185:7): Transit absorption is function that can take 3 arguments ──
Error in `as.data.frame.default(transit)`: cannot coerce class 'c("simpleWarning", "warning", "condition")' to a data.frame
Backtrace:
    █
 1. ├─testthat::expect_equal(...) test-transit.R:185:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. ├─base::as.data.frame(transit)
 5. └─base::as.data.frame.default(transit)
── Error (test-transit.R:207:7): Transit absorption can take numeric arguments ──
Error in `as.data.frame.default(transit)`: cannot coerce class 'c("simpleWarning", "warning", "condition")' to a data.frame
Backtrace:
    █
 1. ├─testthat::expect_equal(...) test-transit.R:207:6
 2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. ├─base::as.data.frame(transit)
 5. └─base::as.data.frame.default(transit)
── Failure (test-ui-piping-single-endpoint.R:24:3): single or multiple endpoint model ──
"lipre" (`actual`) not equal to .tmp$predDf$var (`expected`).

`actual` is a character vector ('lipre')
`expected` is NULL
── Failure (test-ui-piping-single-endpoint.R:48:3): single or multiple endpoint model ──
"lipre" (`actual`) not equal to .tmp$predDf$var (`expected`).

`actual` is a character vector ('lipre')
`expected` is NULL
```

**Comment by billdenney** [comment]
I just ran these locally on Linux (as of 4e1dcda), and I get no errors (0 fail, 4 warn, 1 skip, 12899 pass).

**Comment by mattfidler** [comment]
I have a similar result on my linux system....

Maybe when you implement the other items we can figure out why it is failing on ci.

For now Im going to merge it and focus on getting nlmixr2 ready

**Pull request merged**
