### PR TITLE
Allow broader tolerance for random tests due to Mac differences

### PR DESCRIPTION
**Pull request by billdenney**
I increased the tolerance on RNG tests so that Mac will pass, and because the precision of the tolerance is not the main goal of the test.

### CODE REVIEW

**Comment by mattfidler** [comment]
Awesome, Thanks @billdenney 

Now "simply" figure out the windows issues for a successful compile again.

**Comment by billdenney** [comment]
Yeah, I took a look at the windows stuff, and those failures are out of my expertise.

**Comment by mattfidler** [comment]
I meant to say 

Now **we** "simply"...  Thanks again for your help

**Comment by mattfidler** [comment]
I looked at them, and I skipped them.  The locking mechanism seems to have changed or something happened to have windows dlls created locked until the process is finished.  Therefore, these tests are currently skipped on windows.  This is the reason why the building of the `rxm` test model was in a separate process (#43)

**Pull request merged**
