### PR TITLE
simplify .plotLog

### PR DESCRIPTION
**Pull request by billdenney**
Simplify and test .plotLog; name .plotTime outputs (applies after #126)

### CODE REVIEW

**Comment by billdenney** [comment]
This is just for the helper function `.plotLog()`.  It's not the plots themselves.  That's why it's more easily testable.

**Comment by mattfidler** [comment]
Well the plots had 100% coverage at one time.  My guess this is still true.  So, a simple before and after should give the changes if any (if I can figure out this new interface to vdiffr)

**Comment by mattfidler** [comment]
To be clear the entire `plots.R`

**Comment by mattfidler** [comment]
I am unsure if it was tested or not.  I double checked it is fine.

Thanks @billdenney

**Pull request merged**
